[tool.commitizen]
allowed_prefixes = ["Merge", "Revert", "Pull request", "fixup!", "squash!"]
annotated_tag = true
bump_message = "bump: version $current_version → $new_version"
changelog_file = "CHANGELOG.md"
gpg_sign = true
major_version_zero = true
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version = "0.1.1"
version_files = [
  "version.txt"
]
version_scheme = "semver"