# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - commit-msg
  - post-checkout
  - post-merge
  - pre-commit
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.13.0
    hooks:
      - id: commitlint
        additional_dependencies: ['@commitlint/config-conventional']
        stages: [commit-msg]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.21.3
    hooks:
      - id: commitizen
        stages: [push]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-json
        exclude: \.vscode\/
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [dockerfile, toml]
      - id: mixed-line-ending
        args: [--fix=no]
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii]
        exclude: \.vscode\/
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
