---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: MegaLinter

on:
  # Trigger mega-linter at every push on develop or main. Action will also be visible from Pull
  # Requests
  pull_request:
  push:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to comment issues
      issues: write
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve
          # performances
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/ci_light@v8
        env:
          GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
