---
# Knope GitHub Action configuration file
name: Knope Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    needs: [build-artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: knope-dev/action@v2.1.0
        with:
          version: 0.13.0
      - run: knope release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
